<!--  Header einfügen -->
<img style="width:80%;" id="image" src="iu.jpg">

# Einfuerung in Python - IU - WS 2023/24
<img style="width:40%;" id="image" src="python.png">

                                                               andreas.huemmer.ext@iu.org



## Hausaufgabe 01
Erreichbare Punktzahl: 10
Abgabedatum: 19.12.2024, 06:00

Füllen Sie folgende Felder aus:

Name:           Sascha Angermann

Matrikelnummer: 102205656

In [31]:
# import os
# os.system('cmd command');

### Augabe 1 (1 Punkt)
Installieren Sie eine Anacondaumgebung auf Ihrem Rechner und führen Sie ein Update der Komponenten durch. Führen Sie die nachfolgende Zelle aus.

In [32]:
# Aufgabe 1 (1 Punkt)
!conda info


     active environment : 01_saschaangermann
    active env location : C:\Users\Infi\anaconda3\envs\01_saschaangermann
            shell level : 1
       user config file : C:\Users\Infi\.condarc
 populated config files : C:\Users\Infi\anaconda3\.condarc
                          C:\Users\Infi\.condarc
          conda version : 24.11.0
    conda-build version : 24.9.0
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.11.0=0
                          __cuda=12.7=0
                          __win=0=0
       base environment : C:\Users\Infi\anaconda3  (writable)
      conda av data dir : C:\Users\Infi\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                  

Erreichte Punkte:  ___ / 1

### Aufgabe 2 (2 Punkte)
Gegeben seien zwei komplexe Zahlen a, b. 

In [33]:
a = 23 + 7j
b = 12 - 42j

print("Zahl a ist: ", a, "  ", "Zahl b ist: ", b, "\n")

Zahl a ist:  (23+7j)    Zahl b ist:  (12-42j) 



a) Führen Sie die arithmetischen Operationen: Addition (a+b), Subtraktion (a-b), Multiplikation (a*b) und Division (a/b) aus und geben Sie folgendes pro Operation aus (2 Punkte):

(23+7j) [Operation] (12-42j) = Erbebnis der Operation 

In [34]:
print(f'{a} + {b} = {a+b}')
print(f'{a} - {b} = {a-b}')
print(f'{a} * {b} = {a*b}')
print(f'{a} / {b} = {a/b}')

(23+7j) + (12-42j) = (35-35j)
(23+7j) - (12-42j) = (11+49j)
(23+7j) * (12-42j) = (570-882j)
(23+7j) / (12-42j) = (-0.009433962264150948+0.550314465408805j)


b) Isolieren Sie die Realteile des der beiden Zahlen, wandeln Sie die Realteile (Typcast) nach int und berechnen Sie Re(a) modulo Re(b) und geben Sie ds Ergebnis als int analog zu Teil a) aus. (1 Punkt)

In [35]:
a_real = int(a.real)
b_real = int(b.real)
print(f'Re{a} mod Re{b} = {a_real % b_real}')


Re(23+7j) mod Re(12-42j) = 11


c) Berechnen Sie das konjugiert kompkexe zu b und geben sie das Ergebnis aus (1 Punikt)

In [36]:
print(f'Ergebnis: {b.conjugate()}')

Ergebnis: (12+42j)


Erreichte Punkte:  ___ / 2

### Aufgabe 3 (2 Punkte)
Gegeben sein ein String. 
- Ermitteln Sie die Indexposition des ersten "," und geben sie diese aus.
- Wieviele Kommatas hat der Text?
- Spearieren sie den String anhand der Kommatas und geben Sie die erhaltenen Teilstrings aus.
- Ermitteln Sie wieviele Wörter der Text enthät und geben sie die Anzahl aus.

  [Text by Guano Apes]

In [37]:
text = "Open your eyes, open your mind \
Proud like a god, don't pretend to be blind \
Trapped in yourself, break out instead \
Beat the machine that works in your head"

print(text)

Open your eyes, open your mind Proud like a god, don't pretend to be blind Trapped in yourself, break out instead Beat the machine that works in your head


In [38]:
first_comma_index = text.find(',')
comma_amount = text.count(',')
word_count = len(text.split(' '))
sub_strings = text.split(',')

print(f'Index des ersten Kommas: {first_comma_index}')
print(f'Anzahl Kommatas: {comma_amount}')
print(f'Anzahl Wörter: {word_count}')

print(f'\nTeilstrings nach Komma separiert:')
for sub_string in sub_strings:
    print(sub_string)

Index des ersten Kommas: 14
Anzahl Kommatas: 3
Anzahl Wörter: 29

Teilstrings nach Komma separiert:
Open your eyes
 open your mind Proud like a god
 don't pretend to be blind Trapped in yourself
 break out instead Beat the machine that works in your head


_____________________________________
Erreichte Punkte:  ___ / 2

### Aufgabe 4 (1 Punkt)
Addieren Sie die beiden Variablen. Welchen Typ hat das Ergebnis? 

In [39]:
zahl = 2
zahlstr = "2"

In [40]:
try:
    zahl_sum = zahl + zahlstr
except TypeError as e:
    print(f'Die Addition von Strings und Integers wirft einen Error vom Typ:\n{type(e)}')
    print(e)

Die Addition von Strings und Integers wirft einen Error vom Typ:
<class 'TypeError'>
unsupported operand type(s) for +: 'int' and 'str'


Addieren Sie die beiden Variablen nun so, dass das Ergebnis vom typ int ist und der Summe der beiden "Zahlen" entspricht.

In [41]:
zahl_sum = zahl + int(zahlstr)
print(f'Ergebnis: {zahl_sum}')
print(f'Typ vom Ergebnis: {type(zahl_sum)}')

Ergebnis: 4
Typ vom Ergebnis: <class 'int'>


________________________________
Erreichte Punkte:  ___ / 1

### Aufgabe 5 (1 Punkt)


SET

Gegeben sind folgende Mengen  

In [42]:
set1 = {1, 2, 3, 4, 5, 6, 7}
set2 = {1, 3, 5, 7, "A", "B", "C"}
set3 = {i*2 for i in range(5)}

var = 2

print(set1, set2, set3)

{1, 2, 3, 4, 5, 6, 7} {1, 3, 5, 'A', 7, 'B', 'C'} {0, 2, 4, 6, 8}


Berechnen Sie die Schnittmengen zwischen set1 und set2, set2 und set3, set1 und set3, sowie die Schmittmenge aller Sets.
Brechnen Sie die Vereinigungsmenge aller Sets.
Geben Sie die Ergebnisse Ihrer Operation aus.
Fügen Sie var (s.o.) zur Vereinigungsmenge hinzu und geben sie das Ergebnis aus.

In [43]:
print(f'Schnittmenge set1 & set2: {set1 & set2}')

print(f'Schnittmenge set2 & set3: {set2 & set3}')

print(f'Schnittmenge set1 & set3: {set1 & set3}')

print(f'Schnittmenge set2 & set3: {set1 & set2 & set3}')

vereinigung_1_2_3 = set1 | set2 | set3
print(f'\nVereinigungsmenge set1, set2 & set3: {vereinigung_1_2_3}')

vereinigung_1_2_3.add(var) # Ist bereits vorhanden, also kein neues Element
print(f'Vereinigungsmenge set1, set2 & set3 + var: {vereinigung_1_2_3}')

Schnittmenge set1 & set2: {1, 3, 5, 7}
Schnittmenge set2 & set3: set()
Schnittmenge set1 & set3: {2, 4, 6}
Schnittmenge set2 & set3: set()

Vereinigungsmenge set1, set2 & set3: {0, 1, 2, 3, 4, 5, 6, 7, 'A', 'C', 8, 'B'}
Vereinigungsmenge set1, set2 & set3 + var: {0, 1, 2, 3, 4, 5, 6, 7, 'A', 'C', 8, 'B'}


________________________________
Erreichte Punkte:  ___ / 1

### Aufgabe 6 (1 Punkt)


Listen

Gegeben sind folgende Listen

In [44]:
liste1 = [1, 2, 3, 4, 5]
liste2 = ["A", "B", "C", 1, 3]

print(liste1, liste2)

[1, 2, 3, 4, 5] ['A', 'B', 'C', 1, 3]


Fügen Sie zu liste2 das Elemment 7 hinzu.
Vereinigen Sie das Ergebnis mit liste1.
Geben Sie die jeweiligen Ergebnisse aus.

Wandeln Sie die vereinigte Liste in ein Set und geben Sie das Ergebnis aus.

In [45]:
liste2.append(7)
liste_1_2 = liste1 + liste2

print(f'liste2 mit element 7: {liste2}')
print(f'\nVereinigung von liste1 und liste2 inkl. Element 7:\n{liste_1_2}')
print(f'\nVereinigungsmenge von liste1 und liste2 inkl. Element 7 (als Set):\n{set(liste_1_2)}')



liste2 mit element 7: ['A', 'B', 'C', 1, 3, 7]

Vereinigung von liste1 und liste2 inkl. Element 7:
[1, 2, 3, 4, 5, 'A', 'B', 'C', 1, 3, 7]

Vereinigungsmenge von liste1 und liste2 inkl. Element 7 (als Set):
{1, 2, 3, 4, 5, 'A', 7, 'C', 'B'}


________________________________
Erreichte Punkte:  ___ / 1

### Aufgabe 7 (1 Punkt)


In [46]:
#Matrizen - list, mumpy

#Gegeben sind die folgenden Matrizen, einmal als Python und einmal als NumPy variante.

In [47]:
matrix1 = [ [1, 3, 5],
            [7, 9, 11],
            [13, 15, 17]]

matrix2 = [ [2, 4, 6],
            [8, 10, 12],
            [14, 16, 18]]

print(matrix1, matrix2)

[[1, 3, 5], [7, 9, 11], [13, 15, 17]] [[2, 4, 6], [8, 10, 12], [14, 16, 18]]


Führen Sie eine Matrixmultiplikation von matrix1 und matrix2 durch und stellen Sie das Ergebnis dar.

In [48]:
def calc_matrix_product(m1, m2):
    matrix_product = [[0 for _m2 in range(len(m2))] for _m1 in range(len(m1))]
    
    for i in range(len(m1)):
        for j in range(len(m2[0])):
            for k in range(len(m1[0])):
                matrix_product[i][j] += m1[i][k] * m2[k][j]
    
    return matrix_product

print(f'Ergebnis der Matrixmultiplikation (Python):\n{calc_matrix_product(matrix1, matrix2)}')

Ergebnis der Matrixmultiplikation (Python):
[[96, 114, 132], [240, 294, 348], [384, 474, 564]]


In [49]:
import numpy as np

np_matrix1 = [ [1, 3, 5],
            [7, 9, 11],
            [13, 15, 17]]

np_matrix2 = [ [2, 4, 6],
            [8, 10, 12],
            [14, 16, 18]]

print(np_matrix1, np_matrix2)

[[1, 3, 5], [7, 9, 11], [13, 15, 17]] [[2, 4, 6], [8, 10, 12], [14, 16, 18]]


Führen Sie eine Matrixmultiplikation von np_matrix1 und np_matrix2 durch und stellen Sie das Ergebnis dar.

In [50]:
print(f'Ergebnis der Matrixmultiplikation (NumPy):\n{np.dot(np_matrix1, np_matrix2)}')

Ergebnis der Matrixmultiplikation (NumPy):
[[ 96 114 132]
 [240 294 348]
 [384 474 564]]


________________________________
Erreichte Punkte:  ___ / 1

### Aufgabe 8 (1 Punkt)


File read mit Fehlerbehandlung

Öffnen Sie die nachfolgenden Dateien in einem Block in der angegebenen Reihenfolge und geben Sie deren Inhalt aus.

nichda.txt
hallo.txt

In [51]:
import logging

file1_name = 'nichda.txt'
file2_name = 'hallo.txt'

try:
    with open(file1_name, 'r') as file1:
        print(f'Inhalt von {file1_name}: {file1.read()}')
        file1.close()

    with open(file2_name, 'r') as file2:
        print(f'Inhalt von {file2_name}: {file2.read()}')
        file2.close()

except FileNotFoundError as e:
    logging.error(f'Datei {e.filename} konnte nicht gefunden werden.')
finally:
    print('Lesen beendet.')

ERROR:root:Datei nichda.txt konnte nicht gefunden werden.


Lesen beendet.


________________________________
Erreichte Punkte:  ___ / 1

**Gesamtpunktzahl:  ___ / 10**